name: Manage Kubeflow Pipelines on GCP. 
description: Build, deploy and run a Kubeflow Pipeline on Google Cloud Platform.
inputs:
  KUBEFLOW_URL:
    description: The endpoint where your Kubeflow UI is running. 
    required: true
  CLIENT_ID:
    description: The IAP client id, which was specified when the kubeflow deployment where setup using IAP.
    required: true
  PIPELINE_CODE_PATH:
    description: The full path name including the filename of the python file that describes the pipeline you want to run on Kubeflow.  This should be relative to the root of the GitHub repository where the Action is triggered.
    required: true
  PIPELINE_FUNCTION:
    description: The name of the function which defines the pipeline in the Python file
    required: true
  PIPELINE_NAME:
    description: The name of the pipeline, this name will be the name of the pipeline in the Kubeflow UI. Defaults to {PIPELINE_FUNCTION}_{GITHUB_SHA}.
    required: false
  PIPELINE_VERSION_NAME:
    description: The name of the pipeline version. Defaults to {PIPELINE_FUNCTION}_{GITHUB_SHA}.
    required: false
  PIPELINE_PARAMETERS_PATH:
    description: Path to a parameters YAML file in your repo; the parameters will be passed to the pipeline.
    required: false
  PIPELINE_PARAMETERS:
    description: YAML string containing parameter values; the parameters will be passed to the pipeline. If both this and PIPELINE_PARAMETERS_PATH are provided, the parameter lists will be merged, but values in this argument will override any matching keys in the file.
    required: false
  ENCODED_GOOGLE_APPLICATION_CREDENTIALS:
    description: The base64 encoded google credentials
    required: true
  EXPERIMENT_NAME: 
    description: The name of the experiment name within which the kubeflow pipeline should run
    required: true
  PIPELINE_NAMESPACE: 
    description: The namespace in which the pipeline should run
    required: true
  RUN_PIPELINE: 
    description: Should github action also trigger the pipeline
    required: false
  RUN_NAME:
    description: Name of the pipeline run. Defaults to {PIPELINE_NAME}_{DATETIME}.
    required: false
  V2_COMPATIBLE:
    description: If the pipeline should be compiled with KFP SDK v2 compatibility
    required: false
  PIPELINE_SERVICE_ACCOUNT:
    description: Specifies which Kubernetes service account this run uses
    required: false
outputs:
  WORKFLOW_URL:
    description: URL that is a link to pipeline in Kubeflow
branding:
  color: 'purple'
  icon: 'upload-cloud'
runs:
  using: 'docker'
  image: 'Dockerfile'
